name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
#      - name: Set up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 17
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#      - name: Generate coverage report
#        continue-on-error: true
#        run: ./gradlew clean :exposed-core:koverXmlReport --continue

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
    
